import { constants, promises as fs } from 'node:fs';
import { createPrivateKey, createPublicKey } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { buildResourcePack, ResourcePackVerifier } from '../electron/core/resource-pack';
import { resourceName } from '../electron/core/pack-resource-name';
import { runtimeFile } from '../electron/core/runtime';
import { pinnedDownload, sha256 } from './lib/pinned-download.mjs';

const [recipeArg, baseArg, keyArg, outputArg, ...flags] = process.argv.slice(2);
if (!recipeArg || !baseArg || !keyArg || !outputArg || flags.some((x) => x !== '--offline'))
  throw new Error(
    'Usage: node --import tsx scripts/build-published-pack.ts recipe-directory base-runtime private-key.pem new-output-directory [--offline]',
  );
const recipeRoot = await fs.realpath(recipeArg);
const recipe = JSON.parse((await runtimeFile(recipeRoot, 'recipe.json', 64 * 1024)).toString());
const lock = JSON.parse((await runtimeFile(recipeRoot, 'source.lock.json', 64 * 1024)).toString());
if (
  lock.schemaVersion !== 1 ||
  !/^[a-z0-9][a-z0-9.-]+$/.test(lock.releaseTag) ||
  !/^[a-zA-Z0-9.-]+\.foliopack$/.test(lock.assetName) ||
  !/^[a-z0-9-]+$/.test(lock.source.prefix)
)
  throw new Error('Invalid publisher source lock.');
const cache = path.resolve('.cache/pack-sources');
const source = await pinnedDownload(lock.source, cache, flags.includes('--offline'));
const license = await pinnedDownload(lock.licenseText, cache, flags.includes('--offline'));
const readMember = (name: string) =>
  execFileSync('tar', ['-xOf', '-', `${lock.source.prefix}/${name}`], {
    input: source,
    maxBuffer: 1024 * 1024,
    timeout: 30_000,
  });
const resources = new Map<string, Buffer>();
for (const [name, expected] of Object.entries(lock.files)) {
  resourceName(name);
  const bytes = readMember(name);
  if (sha256(bytes) !== expected) throw new Error(`Changed source member: ${name}`);
  resources.set(name, bytes);
}
for (const [name, value] of Object.entries(lock.supplementalFiles ?? {}) as [
  string,
  { sha256: string },
][]) {
  resourceName(name);
  const bytes = await runtimeFile(path.join(recipeRoot, 'vendor'), name, 1024 * 1024);
  if (resources.has(name) || sha256(bytes) !== value.sha256)
    throw new Error(`Changed supplemental resource: ${name}`);
  resources.set(name, bytes);
}
const extraArchives = new Map<string, Buffer>();
const extraNotices: Buffer[] = [];
for (const extra of lock.extraSources ?? []) {
  const bytes = await pinnedDownload(extra.archive, cache, flags.includes('--offline'));
  extraArchives.set(extra.archive.filename, bytes);
  const member = (name: string) => {
    if (
      !/^[a-zA-Z0-9._/-]+$/.test(name) ||
      name.startsWith('/') ||
      name.split('/').some((p) => p === '..')
    )
      throw new Error('Invalid source archive member.');
    return execFileSync('tar', ['-xOf', '-', name], {
      input: bytes,
      maxBuffer: 1024 * 1024,
      timeout: 30_000,
    });
  };
  for (const [name, value] of Object.entries(extra.files) as [
    string,
    { member: string; sha256: string },
  ][]) {
    resourceName(name);
    const data = member(value.member);
    if (resources.has(name) || sha256(data) !== value.sha256)
      throw new Error(`Duplicate or changed resource: ${name}`);
    resources.set(name, data);
  }
  extraNotices.push(
    Buffer.from(
      `\n--- ${extra.id}: unmodified resources and source materials ---\n` +
        `License identifiers: ${extra.license}\n` +
        `Complete source/material archive: https://github.com/grawish/folio/releases/download/${lock.releaseTag}/${extra.archive.filename}\n` +
        `SHA-256: ${extra.archive.sha256}\n` +
        (extra.id.startsWith('cm')
          ? 'Computer Modern resources by Donald E. Knuth are unmodified; modified font files must be renamed.\n'
          : ''),
    ),
  );
  for (const name of extra.notices)
    extraNotices.push(Buffer.from(`\n--- ${name} (unmodified) ---\n`), member(name));
}
const sourceURL = `https://github.com/grawish/folio/releases/download/${lock.releaseTag}/${lock.source.filename}`;
const notices = Buffer.concat([
  Buffer.from(
    `Folio table resource pack: ${lock.package} ${lock.version}\n\n` +
      `The included ${Object.keys(lock.files).join(', ')} are unchanged upstream files.\n` +
      'Their LPPL terms are separate from the noncommercial terms on original Folio code.\n' +
      'Folio integration questions belong to grawish/folio; no upstream endorsement is implied.\n\n' +
      `Complete unmodified source: ${sourceURL}\n` +
      `Upstream source: ${lock.source.url}\n` +
      `Source SHA-256: ${lock.source.sha256}\n` +
      'Regenerate the .sty files by running tex multirow.ins in that source directory.\n' +
      'The Folio pack preserves the upstream generated bytes; no package files were edited.\n\n' +
      '--- Upstream README (unmodified) ---\n',
  ),
  readMember('README'),
  Buffer.from('\n--- LPPL 1.3c (unmodified) ---\n'),
  license,
  ...extraNotices,
]);
const keyPath = path.resolve(keyArg);
const privateKey = createPrivateKey(
  await runtimeFile(await fs.realpath(path.dirname(keyPath)), path.basename(keyPath), 16 * 1024),
);
const publisher = JSON.parse(await fs.readFile('resources/pack-publisher.json', 'utf8'));
const publicPem = createPublicKey(privateKey).export({ type: 'spki', format: 'pem' }).toString();
if (publisher.keys[recipe.keyId] !== publicPem)
  throw new Error('The private key does not match the reviewed publisher public key.');
const built = await buildResourcePack({
  ...recipe,
  baseRoot: await fs.realpath(baseArg),
  resources,
  notices: notices.toString('utf8'),
  probe: (await runtimeFile(recipeRoot, 'probe.tex', 256 * 1024)).toString('utf8'),
  privateKey,
});
const verified = new ResourcePackVerifier(publisher.keys, publisher.retiredKeys).read(
  built.archive,
);
const output = path.resolve(outputArg);
await fs.mkdir(output, { mode: 0o700 }); // Refuse an existing publication directory.
const artifacts = new Map<string, Buffer>([
  [lock.assetName, built.archive],
  [lock.source.filename, source],
  ['LPPL-1.3c.txt', license],
  ['NOTICES.txt', notices],
  ...extraArchives,
]);
const sourceRecord = Buffer.from(
  JSON.stringify(
    {
      ...lock,
      resourcesModified: false,
      privateKeyIncluded: false,
      base: verified.base,
      target: verified.target,
    },
    null,
    2,
  ) + '\n',
);
artifacts.set('SOURCE.json', sourceRecord);
for (const [name, bytes] of artifacts) {
  const handle = await fs.open(
    path.join(output, name),
    constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY,
    0o600,
  );
  try {
    await handle.writeFile(bytes);
    await handle.sync();
  } finally {
    await handle.close();
  }
}
const assets = [...artifacts].map(([name, bytes]) => ({
  url: `https://github.com/grawish/folio/releases/download/${lock.releaseTag}/${name}`,
  bytes: bytes.length,
  sha256: sha256(bytes),
}));
const { id, title, description, base, target, packages } = verified;
const publication = {
  schemaVersion: 1,
  packs: [{ id, title, description, base, target, packages, artifact: assets[0] }],
  materials: assets.slice(1),
};
await fs.writeFile(
  path.join(output, 'publication.json'),
  JSON.stringify(publication, null, 2) + '\n',
  { flag: 'wx' },
);
await fs.writeFile(
  path.join(output, 'SHA256SUMS'),
  [...artifacts].map(([name, bytes]) => `${sha256(bytes)}  ${name}`).join('\n') + '\n',
  { flag: 'wx' },
);
console.log(JSON.stringify({ output, ...publication }, null, 2));
